apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: infra-nginx-ingress-trial
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 80  
      nodePort: 30000 

