apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-service
spec:
  selector:
    app.kubernetes.io/name: infra-nginx-ingress-trial
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80  

